### ISSUE TITLE
Needs License

### ISSUE THREAD

**Issue by LeifAndersen** [stephanh42/RacketGL#18]
This library should have a license added to it. I would be happy to submit a PR with possible licenses.

Two I would recommend are:

1. Apache v2
2. LGPL v2/3

**Comment by stephanh42** [comment]
Hi Leif,

Please go ahead with your PR.

Thanks,

Stephan

2017-07-17 18:55 GMT+02:00 Leif Andersen <notifications@github.com>:

**Comment by LeifAndersen** [comment]
Okay thanks. I have submitted it, PR #19. If you would rather use a different license I would be happy to change it.

**Comment by stephanh42** [comment]
Thanks. I have merged it.

Stephan

2017-07-18 15:55 GMT+02:00 Leif Andersen <notifications@github.com>:

**Comment by LeifAndersen** [comment]
Okay cool. In that case I'll close this issue. Thank you.
